### PR TITLE
[FINAL] Feature/countdown

### PR DESCRIPTION
**Pull request by MiguelCarranza**
screen shot 2016-12-08 at 11 44 54 pm

Basic countdown clock. Parameters (GET):

  * `to`: Timestamp in milliseconds
  * `label`: Optional parameter, displayed under the countdown

### CODE REVIEW

**Comment by MiguelCarranza** [comment]
Style can be changed. Also, forgive my rusty JS.

**Comment by avand** [comment]
What time zone is timestamp in. UTC I suspect?

**Comment by MiguelCarranza** [comment]
@avand  no, it's all based in local. I should probably improve that, I just went for the simplest approach. But you're right, that can cause many headaches

**Comment by avand** [comment]
Local is fine! No problem there.

**Comment by avand** [comment]
Was just wondering if we could pass some simple date format like `2016-12-11-1700`. That would be a bit an improvement worth making.

**Comment by MiguelCarranza** [comment]
I was going to build another website with a datepicker that would redirect to this guy with the right params... but I guess [this](http://www.epochconverter.com/) suffices

**Comment by avand** [comment]
Can you just link to that site (in a new window) on the countdown page in the event a `to` param is not supplied? That would make it easy to at least click through, get the epoch time, and come back.

**Comment by MiguelCarranza** [comment]
@avand doing something like `Date.parse('2016-12-09 07:52:01)` was my first idea, but its behavior is not consistent. It seems to only work fine on Chrome, unless using RFC2822, which I guess is as confusing as passing a timestamp. I'll figure out something tomorrow in the morning.

**Comment by MiguelCarranza** [comment]
@avand 
screen shot 2016-12-09 at 11 18 56 am

**Pull request merged**
